<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer:  Input neurones,  they'll be two input neurons that taking our model or each of the raw data
### Hidden Layer: Where our ensemble of predictive models is stored
### Output Layer: one output neuron for each variable we want to predict
### Neuron: cell
### Weight: numbers, paramters the network connection between input neuron and second layer neuron should have
### Activation Function: a combination (sum) of all activations from first layer and their weights, negatives used to show dark nodes (sigmoid function) thats comes up with a number between 0 and 1, well for each neuron!
### Node Map: diagrams showcasing inputs, hiden cells, and output layers 
### Perceptron:


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### Let's say We have bunch of numbers that we make into an arrays then a vector, basically input layer takes all that infomation in numbers, depending on the weights it'll lit up the next layer minus teh bias through the activation function calculation later (but for faster training the relu functions makes it faster and simpler to implement!) all the way to the ouput layer.

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [13]:
import pandas as pd
import numpy as np
data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [65]:
df.head()

x1  x2  y
0   0   0  1
1   1   0  1
2   0   1  1
3   1   1  0

In [78]:
correct_outputs = [[1], [1], [1], [0]]

In [79]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1 - sx)

In [80]:
# initialze random weights for inputs

In [81]:
weights = 2 * np.random.random((3,1)) - 1

In [82]:
weights

array([[ 0.53937821],
       [ 0.60096248],
       [-0.44532557]])

In [83]:
# Calculate the weighted sum of inputs ans weights

In [84]:
weighted_sum = np.dot(df, weights)
weighted_sum

array([[-0.44532557],
       [ 0.09405264],
       [ 0.1556369 ],
       [ 1.14034069]])

In [85]:
# Activated value 

activated_output = sigmoid(weighted_sum)
activated_output 

array([[0.39047273],
       [0.52349584],
       [0.53883087],
       [0.75774218]])

In [86]:
error = correct_outputs - activated_output
error

array([[ 0.60952727],
       [ 0.47650416],
       [ 0.46116913],
       [-0.75774218]])

In [87]:
adjusted = error = sigmoid_derivative(activated_output)
adjusted

array([[0.24070772],
       [0.233625  ],
       [0.23269712],
       [0.21728845]])

In [88]:
weights += np.dot(df.T, adjusted)
weights

array([[0.99029166],
       [1.05094805],
       [0.26170426]])

In [89]:
for iteration in range (100000):
    weighted_sum = np.dot(df, weights)
    
    activated_output = sigmoid(weighted_sum)
    
    error = correct_ouputs  - activated_output
    adjustments = error * sigmoid_derivative(activated_output)
    
    weights += np.dot(df.T, adjustments)
 
print('weights after training')
print(weights)

print('Output after training')
print(activated_output)

weights after training
[[-4.95403962]
 [-4.95395383]
 [15.13425447]]
Output after training
[[9.99999733e-01]
 [9.99962088e-01]
 [9.99962091e-01]
 [4.97732313e-05]]


In [90]:
#and that ladies and gentlmen is 99%

## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [93]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [98]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

scaler = MinMaxScaler()

X = scaler.fit_transform(diabetes[feats])

In [99]:
y = diabetes.values[:,-1]
y[:50]

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.])

In [113]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = 'niter'
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1 - sx)

    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """
#       add in bias
#       X = np.append(X_, np.ones_like(X_[0]), axis=1)
        # Randomly Initialize Weights
        self.weights = np.random.random((X.shape[1], 1))

    for i in range(self.niter):
        # Weighted sum of inputs / weights
        weighted_sum = np.dot(X, self.weights)
        # Activate!
        activated_ouput = self.__sigmoid(weighted_sum)
        # Cac error
        error = y - activated_output
        # Update the Weights


    def predict(self, X):
        """Return class label after unit step"""
    
        weighted_sum = np.dot(X, self.weights)
        activated_output = self.__signoid(weighted_sum)
        
        return activated_output

NameError: name 'self' is not defined

In [ ]:
p = Perceptron()
p.fit(X,y)

In [ ]:
p.perdict(X)

In [ ]:
y - p.predict(X)

In [3]:
class Perceptron:
    def __init__(self):
        
        self.inputs = 2 
        self.outputs = 1
        
        self.weights = np.random.randn(self.inputs, sefl.outputs)
        bias = 1
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        return s * (1 - s)
    
    def feed_forward(self, X):
        """ Calculate the NN inference using feed forward aka predict"""
        
        # Weighted sum of inputs +> hidden layer
        self.weighted_sum = np.dot(X, self.weights) + bias
        

In [2]:
from keras.models import Sequential

Using TensorFlow backend.


In [108]:
import tensorflow as tf

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?